classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.pki.authority
- system.reclass.storage.salt
- cluster.mk24_lab_ovs_dvr_vlan_bm
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/dis-xcom/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:kvm:config:node01:admin_ip}
    single_address: ${_param:kvm:config:node01:admin_ip}
    salt_master_host: ${_param:kvm:config:node01:admin_ip}
  reclass:
    storage:
      node:
### openstack compute
        openstack_compute_node01:
              name: cmp01
              domain: ${_param:cluster:domain}
              classes:
              - cluster.${_param:cluster:name}.openstack.compute
              params:
                salt_master_host: ${_param:reclass_config_master}
                linux_system_codename: trusty
                single_address: 172.17.33.106
