parameters:
  reclass:
    storage:
      node:
### monitoring
        monitoring_service_node01:
          name: mon01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.monitoring.server
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:monitoring_service_node01_address}
        monitoring_service_node02:
          name: mon02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.monitoring.server
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:monitoring_service_node02_address}
        monitoring_service_node03:
          name: mon03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.monitoring.server
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:monitoring_service_node03_address}

### opencontrail analytics
        opencontrail_analytics_node01:
          name: nal01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.opencontrail.analytics
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_analytics_node01_address}
            keepalived_vip_priority: 103
            opencontrail_database_id: 1
        opencontrail_analytics_node02:
          name: nal02
          domain: ${_param:cluster:domain}
          classes:  
          - cluster.${_param:cluster:name}.opencontrail.analytics
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_analytics_node02_address}
            keepalived_vip_priority: 102
            opencontrail_database_id: 2
        opencontrail_analytics_node03:
          name: nal03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.opencontrail.analytics
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_analytics_node03_address}
            keepalived_vip_priority: 101
            opencontrail_database_id: 3

### opencontrail network node
        opencontrail_control_node01:
          name: ntw01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.opencontrail.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_control_node01_address}
            keepalived_vip_priority: 103
            opencontrail_database_id: 1
        opencontrail_control_node02:
          name: ntw02
          domain: ${_param:cluster:domain}
          classes:  
          - cluster.${_param:cluster:name}.opencontrail.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_control_node02_address}
            keepalived_vip_priority: 102
            opencontrail_database_id: 2
        opencontrail_control_node03:
          name: ntw03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.opencontrail.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_control_node03_address}
            keepalived_vip_priority: 101
            opencontrail_database_id: 3

### neutron gateway
        opencontrail_gateway_node01:
          name: gtw01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.opencontrail.gateway
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:opencontrail_gateway_address}

        openstack_gateway_node01:
          name: gtw02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.gateway
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_gateway_address}parameters:

### openstack compute
        openstack_compute_node01:
          name: cmp01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: 172.17.33.106
        openstack_compute_node02:
          name: cmp02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: 172.17.33.107
        openstack_compute_node03:
          name: cmp03
          domain: ${_param:cluster:domain}
          classes: 
          - cluster.${_param:cluster:name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: 172.17.33.108

### openstack controller
        openstack_control_node01:
          name: ctl01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_control_node01_address}
            keepalived_vip_priority: 103
            opencontrail_database_id: 1
            rabbitmq_cluster_role: master
        openstack_control_node02:
          name: ctl02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_control_node02_address}
            keepalived_vip_priority: 102
            opencontrail_database_id: 2
            rabbitmq_cluster_role: slave
        openstack_control_node03:
          name: ctl03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_control_node03_address}
            keepalived_vip_priority: 101
            opencontrail_database_id: 3
            rabbitmq_cluster_role: slave

### openstack database
        openstack_database_node01:
          name: dbs01
          domain: ${_param:cluster:domain}
          classes:
          - service.galera.master.cluster
          - cluster.${_param:cluster:name}.openstack.database
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_database_node01_address}
            keepalived_vip_priority: 103
            mysql_cluster_role: master
        openstack_database_node02:
          name: dbs02
          domain: ${_param:cluster:domain}
          classes:  
          - service.galera.slave.cluster
          - cluster.${_param:cluster:name}.openstack.database
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_database_node02_address}
            keepalived_vip_priority: 102
            mysql_cluster_role: slave
        openstack_database_node03:
          name: dbs03
          domain: ${_param:cluster:domain}
          classes:
          - service.galera.slave.cluster
          - cluster.${_param:cluster:name}.openstack.database
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_database_node03_address}
            keepalived_vip_priority: 101
            mysql_cluster_role: slave

### openstack amqp
        openstack_message_queue_node01:
          name: msg01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.message_queue
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_message_queue_node01_address}
            keepalived_vip_priority: 103
            rabbitmq_cluster_role: master
        openstack_message_queue_node02:
          name: msg02
          domain: ${_param:cluster:domain}
          classes:  
          - cluster.${_param:cluster:name}.openstack.message_queue
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_message_queue_node02_address}
            keepalived_vip_priority: 102
            rabbitmq_cluster_role: slave
        openstack_message_queue_node03:
          name: msg03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.message_queue
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_message_queue_node03_address}
            keepalived_vip_priority: 101
            rabbitmq_cluster_role: slave

### openstack proxy
        openstack_proxy_node01:
          name: prx01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.proxy
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_proxy_node01_address}
        openstack_proxy_node02:
          name: prx02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.openstack.proxy
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:openstack_proxy_node02_address}

### baremetal kvm
        fuel_compute_node01:
          name: kvm01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node01_address}
            deploy_address: ${_param:fuel_compute_node01_deploy_address}
        fuel_compute_node02:
          name: kvm02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node02_address}
            deploy_address: ${_param:fuel_compute_node02_deploy_address}
        fuel_compute_node03:
          name: kvm03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node03_address}
            deploy_address: ${_param:fuel_compute_node03_deploy_address}
        fuel_compute_node04:
          name: kvm04
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node04_address}
            deploy_address: ${_param:fuel_compute_node04_deploy_address}
        fuel_compute_node05:
          name: kvm05
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node05_address}
            deploy_address: ${_param:fuel_compute_node05_deploy_address}
        fuel_compute_node06:
          name: kvm06
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node06_address}
            deploy_address: ${_param:fuel_compute_node06_deploy_address}
        fuel_compute_node07:
          name: kvm07
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node07_address}
            deploy_address: ${_param:fuel_compute_node07_deploy_address}
        fuel_compute_node08:
          name: kvm08
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node08_address}
            deploy_address: ${_param:fuel_compute_node08_deploy_address}
        fuel_compute_node09:
          name: kvm09
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.fuel.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: trusty
            single_address: ${_param:fuel_compute_node09_address}
            deploy_address: ${_param:fuel_compute_node09_deploy_address}

### staklight log
        stacklight_log_node01:
          name: log01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.log
          - cluster.${_param:cluster:name}.stacklight.log_curator
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_log_node01_address}
            keepalived_vip_priority: 103
        stacklight_log_node02:
          name: log02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.log
          - cluster.${_param:cluster:name}.stacklight.log_curator
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_log_node02_address}
            keepalived_vip_priority: 102
        stacklight_log_node03:
          name: log03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.log
          - cluster.${_param:cluster:name}.stacklight.log_curator
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_log_node03_address}
            keepalived_vip_priority: 101

### stacklight monitor
        stacklight_monitor_node01:
          name: mon01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.monitor
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node01_address}
            keepalived_vip_priority: 103
        stacklight_monitor_node02:
          name: mon02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.monitor
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node02_address}
            keepalived_vip_priority: 102
        stacklight_monitor_node03:
          name: mon03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.monitor
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node03_address}
            keepalived_vip_priority: 101

### stacklight server
        stacklight_server_node01:
          name: mon01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.server
          - system.influxdb.server.single
          - system.elasticsearch.client.single
          - system.grafana.client.single
          - system.kibana.client.single
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node01_address}
            keepalived_vip_priority: 103
        stacklight_server_node02:
          name: mon02
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.server
          - system.influxdb.server.single
          - system.elasticsearch.client.single
          - system.grafana.client.single
          - system.kibana.client.single
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node02_address}
            keepalived_vip_priority: 102
        stacklight_server_node03:
          name: mon03
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.server
          - system.influxdb.server.single
          - system.elasticsearch.client.single
          - system.grafana.client.single
          - system.kibana.client.single
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_monitor_node03_address}
            keepalived_vip_priority: 101

### stacklight telemetry
        stacklight_telemetry_node01:
          name: mtr01
          domain: ${_param:cluster:domain}
          classes:
          - cluster.${_param:cluster:name}.stacklight.telemetry
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:stacklight_telemetry_node01_address}
            keepalived_vip_priority: 103
